/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
});
export const SubmitContactRequest = IDL.Record({
  'service' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const SubmitContactResult = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContact' : IDL.Func([SubmitContactRequest], [SubmitContactResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
  });
  const SubmitContactRequest = IDL.Record({
    'service' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const SubmitContactResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [SubmitContactRequest],
        [SubmitContactResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };